config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get "all_post" => "posts#all_post"
      get "featured" => "posts#featured"
      get "trending" => "posts#trending"
      get "news" => "posts#news"
      get "events" => "posts#events"
      get "latest" => "posts#latest"
      get "tech" => "posts#tech"
  end  
end
resources :posts do
  resources :comments, only: [:edit, :update, :show, :destroy, :create]
  get 'comments/all', on: :member
end  

  require 'sidekiq/web'
  
  mount ActionCable.server => '/cable' 
  mount Sidekiq::Web => '/sidekiq'
  
  get 'private/test'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'users/get_invited_user', to: 'users#get_invited_user'
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  },
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    root to: 'users/sessions#new'
    resources :users  do
      collection do
        get "authenticate" => "users/sessions#authenticate_user"
    end
  end     
  end
 
  resources :member_details

end

app/models/member_detail.rb
class MemberDetail < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar, dependent: :purge_later
  before_save :set_correct_attachment_filenames

  def set_correct_attachment_filenames
    if self.avatar.attached?
      ActiveRecord::Base.transaction do
        begin
          self.avatar.blob.update(key: "AvatarImage_User-#{user_id}.#{self.avatar.filename.extension}")
        rescue => e
          # Handle the exception, e.g., log the error or take appropriate action
          # You can use this for debugging
        end
      end
    end
  end
  
 
  
end

app/controllers/member_details_controller.rb
class MemberDetailsController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_user_id, except:[:update]   
  def member_detail_params
    params.require(:member_detail).permit(:status, :role, :avatar, :biography, :social_media_links)
  end

  def show  
    user_id = params[:id].to_i
    @memberdetail = MemberDetail.where({id: params[:id]}).first

    if @memberdetail.nil?    
      render json: { error: "member details not found" }, status: :not_found     
    else                   
      render json: {
        status: {code: 200, message: 'ok.'},
        data: MemberDetailSerializer.new(@memberdetail).serializable_hash[:data][:attributes],
      }, status: :ok
    end     
  end
  
  def set_user_id
    @user_id=User.friendly.find(params["id"])["id"]
  end  

  def edit       
   
    @member = MemberDetail.find_by(user_id:@user_id)
  end  
  def set_filename
    
  end
  def update                 
     @member_detail = MemberDetail.find_by(user_id: current_user.id)        
     
       if @member_detail.update(member_detail_params)
         render json: {
        status: {code: 200, message: 'ok.'},
        data: MemberDetailSerializer.new(@member_detail).serializable_hash[:data][:attributes],
      }, status: :ok
       else
        render json: { error: "unprocessible entity" }, status: :not_found     
       end     
   end
end

app/helpers/member_details_helper.rb
module MemberDetailsHelper
    def avatar_helper(user)        
        avatar_image =  @member&.avatar&.url&.split("?")&.first || gravatar_url
        image_tag(avatar_image, width: 45, height: 45, class: "profile-image")
      end
      def gravatar_url
        "https://gravatar.com/avatar/f2709d75b2a3868b82f5f52947410304?s=400&d=robohash&r=x"
      end
end

app/views/member_details/edit.html.erb
<!-- app/views/member_details/edit.html.erb -->

<!-- Your form or other content here -->
<div class="container-md">
        <div class="row">
         
          <div class="col-10 col-md-10 m-auto">

            <!-- Card -->
            <div class="card card-bleed shadow-light-lg mb-6">
              <div class="card-header">

                <!-- Heading -->
                <h4 class="mb-0">
                  Basic Information
                </h4>

              </div>
              <div class="card-body">
                <%= form_for @member, url: member_detail_path, method: :put do |f| %>
                      <div class="row">                   
                        <div class="form-group col-6">
                          <%= f.label :status %>
                          <%= f.select :status, [["Active", "active"], ["Inactive", "inactive"]], {}, class: "form-control" %>
                        </div>
                         <div class="form-group  col-6">
                            <%= f.label :role %>
                            <%= f.select :role, [["Guest", "guest"], ["Author", "author"], ["SuperAdmin", "superadmin"]], {}, class: "form-control" %>
                         </div>
                       
                        <div class="form-group   col-6 ">                                                                                             
                          <div  class="col py-2">
                            <%= f.label :social_media_links, 'Social Media Link' %>                            
                            <%= f.text_field :social_media_links, class: 'form-control' %>
                          </div>                                                                                                                                             
                            <div class="field my-2">
                            <%if avatar_helper(@member)%>
                             <span><%=link_to avatar_helper(@member), @member&.avatar&.url&.split("?")&.first||gravatar_url  %></span>
                            <%end%> 
                            <div>
                           
                            </div> 
                            <%= f.label :avatar, 'Avatar',class: "" %>
                            <%= f.file_field :avatar %>
                          </div>
                         <div class="form-group  col-12">
                            <%= f.label :biography %>
                            <%= f.text_area :biography, class: "form-control"    %>
                         </div>
                         
                         </div>  
                            <div class="actions">
                            <%= f.submit "Submit", class: "btn btn-primary" %>
                            </div>    
                         </div>                                                                         
                        </div>
                  <!-- Add more form fields for other attributes as needed -->
                 
                <% end %>
              </div>
            </div>  
          </div>
        </div> <!-- / .row -->
      </div>